#!/usr/bin/env python3
# Render a monospace TrueType font into a 12x24 1-bpp bitmap font header (ASCII 32..126).
# Each glyph: 24 rows x 16-bit little-endian words, bit 15 = leftmost pixel (12 used).
import sys
from PIL import Image, ImageFont, ImageDraw
W,H=12,24; path=sys.argv[1] if len(sys.argv)>1 else "/System/Library/Fonts/Menlo.ttc"; out=sys.argv[2] if len(sys.argv)>2 else "v5f/font12x24.h"
best=None
for size in range(24,14,-1):                    # largest size whose glyphs fit the 12x24 cell
    f=ImageFont.truetype(path,size)
    asc,desc=f.getmetrics(); ok=True; maxw=0
    for c in range(32,127):
        l,t,r,b=f.getbbox(chr(c)); maxw=max(maxw,r)
        if r>W or asc+desc>H: ok=False; break
    if ok: best=(size,f,asc,desc); break
size,f,asc,desc=best; yoff=(H-(asc+desc))//2
lines=[f"/* 12x24 bitmap font generated by tools/mkfont.py from {path.split('/')[-1]} at {size} px; ASCII 32..126, 24 rows/glyph, bit 15 = left pixel */",
       "#ifndef FONT12X24_H","#define FONT12X24_H","#include <stdint.h>","#define FONT_W 12","#define FONT_H 24","static const uint16_t font12x24[95][24] = {"]
for c in range(32,127):
    im=Image.new("1",(W,H),0); d=ImageDraw.Draw(im); d.text((0,yoff),chr(c),font=f,fill=1)
    rows=[]
    for y in range(H):
        v=0
        for x in range(W):
            if im.getpixel((x,y)): v|=0x8000>>x
        rows.append(v)
    lines.append("    {"+",".join(f"0x{v:04X}" for v in rows)+"}, /* '%s' */" % (chr(c).replace('\\','\\\\')))
lines+=["};","#endif"]
open(out,"w").write("\n".join(lines)+"\n"); print(f"font: {path.split('/')[-1]} size {size}px, ascent {asc} descent {desc}, yoff {yoff} -> {out}")
# preview a few glyphs
def show(c):
    im=Image.new("1",(W,H),0); ImageDraw.Draw(im).text((0,yoff),c,font=f,fill=1)
    return ["".join("#" if im.getpixel((x,y)) else "." for x in range(W)) for y in range(H)]
for r in zip(*(show(c) for c in "Ag8W/")): print("   "+"  ".join(r))
